// Constants for the application
export const API_BASE = "http://127.0.0.1:8000";

export const MLB_TEAMS = [
  { abbrev: "AZ", name: "Arizona Diamondbacks" },
  { abbrev: "ATH", name: "Athletics" },
  { abbrev: "ATL", name: "Atlanta Braves" },
  { abbrev: "BAL", name: "Baltimore Orioles" },
  { abbrev: "BOS", name: "Boston Red Sox" },
  { abbrev: "CHC", name: "Chicago Cubs" },
  { abbrev: "CWS", name: "Chicago White Sox" },
  { abbrev: "CIN", name: "Cincinnati Reds" },
  { abbrev: "CLE", name: "Cleveland Guardians" },
  { abbrev: "COL", name: "Colorado Rockies" },
  { abbrev: "DET", name: "Detroit Tigers" },
  { abbrev: "HOU", name: "Houston Astros" },
  { abbrev: "KC", name: "Kansas City Royals" },
  { abbrev: "LAA", name: "Los Angeles Angels" },
  { abbrev: "LAD", name: "Los Angeles Dodgers" },
  { abbrev: "MIA", name: "Miami Marlins" },
  { abbrev: "MIL", name: "Milwaukee Brewers" },
  { abbrev: "MIN", name: "Minnesota Twins" },
  { abbrev: "NYM", name: "New York Mets" },
  { abbrev: "NYY", name: "New York Yankees" },
  { abbrev: "PHI", name: "Philadelphia Phillies" },
  { abbrev: "PIT", name: "Pittsburgh Pirates" },
  { abbrev: "SD", name: "San Diego Padres" },
  { abbrev: "SF", name: "San Francisco Giants" },
  { abbrev: "SEA", name: "Seattle Mariners" },
  { abbrev: "STL", name: "St. Louis Cardinals" },
  { abbrev: "TB", name: "Tampa Bay Rays" },
  { abbrev: "TEX", name: "Texas Rangers" },
  { abbrev: "TOR", name: "Toronto Blue Jays" },
  { abbrev: "WSH", name: "Washington Nationals" },
];
